import { v4 as uuidv4 } from 'uuid'

export const LEGAL_ORDERS = [
  'Russia',
  'Germany',
  'France',
  'Netherlands',
  'Switzerland',
  'Austria',
  'England/USA',
  'Roman law',
  'EU',
  'International',
  'Spain',
  'Italy',
  'Other',
]

export const TOPICS = [
  'General Civil Law',
  'Property Law',
  'Contract Law',
  'Obligations',
  'Tort Law',
  'Corporate Law',
  'Pledge/Security',
  'Invalidity of Transactions',
  'Family Law',
  'Inheritance Law',
  'Procedural Law',
  'Comparative Law',
  'Legal History',
  'Legal Theory',
  'Roman Law',
  'Bankruptcy',
  'Intellectual Property Law',
  'Other',
]

export const TOPIC_COLORS = {
  'General Civil Law': '#c8a850',
  'Property Law': '#4a7ab0',
  'Contract Law': '#7a4ab0',
  'Obligations': '#b04a7a',
  'Tort Law': '#b07a4a',
  'Corporate Law': '#4ab07a',
  'Pledge/Security': '#4ab0b0',
  'Invalidity of Transactions': '#b04a4a',
  'Family Law': '#b0884a',
  'Inheritance Law': '#7ab04a',
  'Procedural Law': '#4a7ab0',
  'Comparative Law': '#8899bb',
  'Legal History': '#9a7a5a',
  'Legal Theory': '#5a7a9a',
  'Roman Law': '#c0704a',
  'Bankruptcy': '#6a4ab0',
  'Intellectual Property Law': '#3a8a7a',
  'Other': '#4a5a70',
}

export const SEED_BOOKS = [
  {
    id: uuidv4(),
    title: 'Пандекты',
    author: 'Windscheid B.',
    year: 1887,
    legalOrder: ['Germany', 'Roman law'],
    topics: ['General Civil Law', 'Obligations'],
    format: 'paper',
    rating: 5,
    description: 'Фундаментальный труд Бернхарда Виндшейда, ставший одним из главных источников для разработчиков Германского гражданского уложения. Систематически излагает пандектное право, основываясь на римско-правовой традиции и её научной обработке немецкой исторической школой. Особое внимание уделяется учению об обязательствах, субъективных правах и общей части гражданского права. Три тома охватывают весь спектр институтов частного права с глубоким доктринальным анализом.',
    tags: ['пандектистика', 'BGB', 'догматика'],
    notes: '',
    yaPath: '',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Система современного римского права',
    author: 'Savigny F.C.',
    year: 1840,
    legalOrder: ['Roman law', 'Germany'],
    topics: ['Legal History', 'General Civil Law'],
    format: 'paper',
    rating: 5,
    description: 'Монументальная восьмитомная работа Фридриха Карла фон Савиньи — основоположника исторической школы права. Книга представляет собой всестороннее изложение системы римского права как живой правовой традиции, пригодной для применения в современных условиях. Автор разрабатывает учение о правоотношении, субъективном праве и его осуществлении, о правовых фактах и действии норм во времени и пространстве. Оказала колоссальное влияние на всю европейскую цивилистику XIX–XX веков.',
    tags: ['историческая школа', 'догматика', 'правоотношение'],
    notes: '',
    yaPath: '',
    createdAt: new Date('2024-01-11').toISOString(),
    updatedAt: new Date('2024-01-11').toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Вещное право',
    author: 'Скловский К.И.',
    year: 2008,
    legalOrder: ['Russia'],
    topics: ['Property Law'],
    format: 'paper',
    rating: 5,
    description: 'Фундаментальный труд ведущего российского цивилиста, посвящённый теории вещного права. Автор исследует природу владения, права собственности и ограниченных вещных прав с позиций как отечественной, так и европейской цивилистической традиции. Книга предлагает концептуально новый взгляд на защиту вещных прав, виндикацию и реституцию. Особый интерес представляет полемика с господствующими доктринами и предложенная автором оригинальная система вещного права для современной России.',
    tags: ['виндикация', 'владение', 'собственность'],
    notes: '',
    yaPath: '',
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Исполнение договорного обязательства',
    author: 'Сарбаш С.В.',
    year: 2005,
    legalOrder: ['Russia'],
    topics: ['Obligations', 'Contract Law'],
    format: 'paper',
    rating: 4,
    description: 'Монография, посвящённая детальному анализу института исполнения договорных обязательств в российском гражданском праве. Автор исследует понятие и принципы исполнения, субъектный состав исполнения, предмет, срок, место и способ исполнения. Значительное внимание уделяется обеспечению исполнения обязательств, удержанию и зачёту. Работа отличается строгостью методологии и широким использованием судебной практики, что делает её ценным источником как для теоретиков, так и для практикующих юристов.',
    tags: ['договор', 'обязательство', 'исполнение'],
    notes: '',
    yaPath: '',
    createdAt: new Date('2024-02-20').toISOString(),
    updatedAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Введение в сравнительное правоведение в сфере частного права',
    author: 'Zweigert K., Kötz H.',
    year: 1998,
    legalOrder: ['Germany', 'France', 'England/USA', 'Other'],
    topics: ['Comparative Law'],
    format: 'paper',
    rating: 5,
    description: 'Классический учебник по сравнительному правоведению, признанный мировым стандартом в своей области. Авторы систематически анализируют основные правовые семьи мира — романо-германскую, англо-американскую, скандинавскую и другие — с точки зрения их исторических корней, юридического стиля и практических решений в ключевых институтах частного права. Вторая часть книги посвящена сравнительному анализу конкретных институтов: договора, деликта, неосновательного обогащения. Незаменимое введение в мировую правовую культуру для любого серьёзного правоведа.',
    tags: ['правовые семьи', 'компаративистика', 'частное право'],
    notes: '',
    yaPath: '',
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-03-01').toISOString(),
  },
]
